// This file is auto-generated by `pnpm --filter @crm/db generate-types`.
// Run `supabase gen types typescript --local > packages/db/types/database.types.ts` after migrations.
// DO NOT edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          role: "admin" | "sales" | "account_manager" | "client";
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          role?: "admin" | "sales" | "account_manager" | "client";
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          role?: "admin" | "sales" | "account_manager" | "client";
          avatar_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      companies: {
        Row: {
          id: string;
          name: string;
          domain: string | null;
          industry: string | null;
          logo_path: string | null;
          owner_id: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          domain?: string | null;
          industry?: string | null;
          logo_path?: string | null;
          owner_id: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          domain?: string | null;
          industry?: string | null;
          logo_path?: string | null;
          owner_id?: string;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "companies_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      contacts: {
        Row: {
          id: string;
          company_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          title: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          title?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          title?: string | null;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contacts_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          }
        ];
      };
      leads: {
        Row: {
          id: string;
          title: string | null;
          contact_name: string | null;
          job_title: string | null;
          company_id: string | null;
          contact_id: string | null;
          email: string | null;
          phone: string | null;
          linkedin_url: string | null;
          industry: string | null;
          location: string | null;
          product_interest: string | null;
          source: string | null;
          status: "new" | "contacted" | "qualified" | "lost";
          assigned_to: string | null;
          value_estimate: number | null;
          next_follow_up_date: string | null;
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title?: string | null;
          contact_name?: string | null;
          job_title?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          email?: string | null;
          phone?: string | null;
          linkedin_url?: string | null;
          industry?: string | null;
          location?: string | null;
          product_interest?: string | null;
          source?: string | null;
          status?: "new" | "contacted" | "qualified" | "lost";
          assigned_to?: string | null;
          value_estimate?: number | null;
          next_follow_up_date?: string | null;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string | null;
          contact_name?: string | null;
          job_title?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          email?: string | null;
          phone?: string | null;
          linkedin_url?: string | null;
          industry?: string | null;
          location?: string | null;
          product_interest?: string | null;
          source?: string | null;
          status?: "new" | "contacted" | "qualified" | "lost";
          assigned_to?: string | null;
          value_estimate?: number | null;
          next_follow_up_date?: string | null;
          notes?: string | null;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "leads_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_assigned_to_fkey";
            columns: ["assigned_to"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      deals: {
        Row: {
          id: string;
          title: string;
          job_title: string | null;
          company_id: string;
          primary_contact_id: string | null;
          stage: "prospect" | "proposal" | "negotiation" | "won" | "lost";
          amount: number;
          product_use_case: string | null;
          probability: number | null;
          next_action: string | null;
          notes: string | null;
          owner_id: string;
          expected_close_date: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title?: string;
          job_title?: string | null;
          company_id: string;
          primary_contact_id?: string | null;
          stage?: "prospect" | "proposal" | "negotiation" | "won" | "lost";
          amount?: number;
          product_use_case?: string | null;
          probability?: number | null;
          next_action?: string | null;
          notes?: string | null;
          owner_id: string;
          expected_close_date?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          job_title?: string | null;
          company_id?: string;
          primary_contact_id?: string | null;
          stage?: "prospect" | "proposal" | "negotiation" | "won" | "lost";
          amount?: number;
          product_use_case?: string | null;
          probability?: number | null;
          next_action?: string | null;
          notes?: string | null;
          owner_id?: string;
          expected_close_date?: string | null;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "deals_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deals_primary_contact_id_fkey";
            columns: ["primary_contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deals_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      activities: {
        Row: {
          id: string;
          entity_type: "company" | "contact" | "lead" | "deal" | "quote" | "invoice";
          entity_id: string;
          type: "note" | "call" | "email" | "meeting" | "system";
          author_id: string;
          body: string;
          occurred_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          entity_type: "company" | "contact" | "lead" | "deal" | "quote" | "invoice";
          entity_id: string;
          type: "note" | "call" | "email" | "meeting" | "system";
          author_id: string;
          body?: string;
          occurred_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          entity_type?: "company" | "contact" | "lead" | "deal" | "quote" | "invoice";
          entity_id?: string;
          type?: "note" | "call" | "email" | "meeting" | "system";
          author_id?: string;
          body?: string;
          occurred_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "activities_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      audit_log: {
        Row: {
          id: string;
          actor_id: string;
          action: string;
          entity_type: string;
          entity_id: string;
          before: Json | null;
          after: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id: string;
          action: string;
          entity_type: string;
          entity_id: string;
          before?: Json | null;
          after?: Json | null;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      products: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          unit_price: number;
          currency: string;
          tax_rate: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          unit_price?: number;
          currency?: string;
          tax_rate?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          unit_price?: number;
          currency?: string;
          tax_rate?: number;
          active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      quotes: {
        Row: {
          id: string;
          deal_id: string;
          company_id: string;
          status: "draft" | "sent" | "approved" | "rejected" | "expired";
          current_version: number;
          created_by: string;
          valid_until: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          company_id: string;
          status?: "draft" | "sent" | "approved" | "rejected" | "expired";
          current_version?: number;
          created_by: string;
          valid_until?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          company_id?: string;
          status?: "draft" | "sent" | "approved" | "rejected" | "expired";
          current_version?: number;
          created_by?: string;
          valid_until?: string | null;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quotes_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quotes_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quotes_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      quote_versions: {
        Row: {
          id: string;
          quote_id: string;
          version_number: number;
          line_items: Json;
          subtotal: number;
          tax: number;
          total: number;
          currency: string;
          pdf_path: string | null;
          is_current: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          quote_id: string;
          version_number: number;
          line_items?: Json;
          subtotal?: number;
          tax?: number;
          total?: number;
          currency?: string;
          pdf_path?: string | null;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          quote_id?: string;
          version_number?: number;
          line_items?: Json;
          subtotal?: number;
          tax?: number;
          total?: number;
          currency?: string;
          pdf_path?: string | null;
          is_current?: boolean;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quote_versions_quote_id_fkey";
            columns: ["quote_id"];
            isOneToOne: false;
            referencedRelation: "quotes";
            referencedColumns: ["id"];
          }
        ];
      };
      quote_approvals: {
        Row: {
          id: string;
          quote_version_id: string;
          magic_link_token: string;
          approved_by_name: string | null;
          approved_by_email: string | null;
          signature_data: string | null;
          approved_at: string | null;
          ip_address: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          quote_version_id: string;
          magic_link_token: string;
          approved_by_name?: string | null;
          approved_by_email?: string | null;
          signature_data?: string | null;
          approved_at?: string | null;
          ip_address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          quote_version_id?: string;
          magic_link_token?: string;
          approved_by_name?: string | null;
          approved_by_email?: string | null;
          signature_data?: string | null;
          approved_at?: string | null;
          ip_address?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quote_approvals_quote_version_id_fkey";
            columns: ["quote_version_id"];
            isOneToOne: false;
            referencedRelation: "quote_versions";
            referencedColumns: ["id"];
          }
        ];
      };
      invoices: {
        Row: {
          id: string;
          quote_id: string;
          company_id: string;
          invoice_number: string;
          status: "draft" | "sent" | "paid" | "overdue" | "void";
          amount_due: number;
          currency: string;
          due_date: string | null;
          stripe_invoice_id: string | null;
          payment_link: string | null;
          account_manager_id: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          quote_id: string;
          company_id: string;
          invoice_number: string;
          status?: "draft" | "sent" | "paid" | "overdue" | "void";
          amount_due?: number;
          currency?: string;
          due_date?: string | null;
          stripe_invoice_id?: string | null;
          payment_link?: string | null;
          account_manager_id?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          quote_id?: string;
          company_id?: string;
          invoice_number?: string;
          status?: "draft" | "sent" | "paid" | "overdue" | "void";
          amount_due?: number;
          currency?: string;
          due_date?: string | null;
          stripe_invoice_id?: string | null;
          payment_link?: string | null;
          account_manager_id?: string | null;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invoices_quote_id_fkey";
            columns: ["quote_id"];
            isOneToOne: false;
            referencedRelation: "quotes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoices_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoices_account_manager_id_fkey";
            columns: ["account_manager_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      payments: {
        Row: {
          id: string;
          invoice_id: string;
          amount: number;
          currency: string;
          stripe_payment_intent_id: string | null;
          status: "pending" | "succeeded" | "failed" | "refunded";
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          amount: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          status?: "pending" | "succeeded" | "failed" | "refunded";
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          amount?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          status?: "pending" | "succeeded" | "failed" | "refunded";
          paid_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id"];
          }
        ];
      };
      follow_ups: {
        Row: {
          id: string;
          invoice_id: string;
          scheduled_for: string;
          channel: "email" | "slack";
          status: "pending" | "sent" | "cancelled";
          attempt_number: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          scheduled_for: string;
          channel: "email" | "slack";
          status?: "pending" | "sent" | "cancelled";
          attempt_number?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          scheduled_for?: string;
          channel?: "email" | "slack";
          status?: "pending" | "sent" | "cancelled";
          attempt_number?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "follow_ups_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id"];
          }
        ];
      };
      integration_connections: {
        Row: {
          id: string;
          user_id: string;
          provider: "google" | "slack";
          access_token: string;
          refresh_token: string | null;
          expires_at: string | null;
          scope: string | null;
          provider_account_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: "google" | "slack";
          access_token: string;
          refresh_token?: string | null;
          expires_at?: string | null;
          scope?: string | null;
          provider_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: "google" | "slack";
          access_token?: string;
          refresh_token?: string | null;
          expires_at?: string | null;
          scope?: string | null;
          provider_account_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "integration_connections_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      calendar_events: {
        Row: {
          id: string;
          deal_id: string | null;
          google_event_id: string;
          title: string;
          start_at: string;
          end_at: string;
          meet_link: string | null;
          synced_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id?: string | null;
          google_event_id: string;
          title: string;
          start_at: string;
          end_at: string;
          meet_link?: string | null;
          synced_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string | null;
          google_event_id?: string;
          title?: string;
          start_at?: string;
          end_at?: string;
          meet_link?: string | null;
          synced_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "calendar_events_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          }
        ];
      };
      slack_channels: {
        Row: {
          id: string;
          deal_id: string;
          slack_channel_id: string;
          channel_name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          slack_channel_id: string;
          channel_name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          slack_channel_id?: string;
          channel_name?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "slack_channels_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<never, never>;
    Functions: {
      current_user_role: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
}
